-- CreateEnum
CREATE TYPE "USER_ROLE" AS ENUM ('USER', 'ADMIN', 'SUPER_ADMIN');

-- AlterTable for User
ALTER TABLE "User" 
ADD COLUMN "notifyOnCreate" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "notifyOnDelete" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "notifyOnUpdate" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "role" "USER_ROLE" NOT NULL DEFAULT 'USER';
